repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=88]
        stages: [commit]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
        stages: [commit]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=88, --extend-ignore=E203]
        stages: [commit]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        additional_dependencies:
            - types-setuptools
            - numpy
            - types-PyYAML
        args: [
            --python-version=3.9,
            --warn-unused-configs,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
            --check-untyped-defs,
            --disallow-untyped-decorators,
            --no-implicit-optional,
            --warn-redundant-casts,
            --warn-unused-ignores,
            --warn-no-return,
            --warn-unreachable
        ]
        stages: [commit]

